services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Valantic\ElasticaBridgeBundle\Command\:
    resource: '../../Command/*'
    tags: [ 'console.command' ]

  Valantic\ElasticaBridgeBundle\Elastica\Client\ElasticsearchClient:
    factory: [ 'Valantic\ElasticaBridgeBundle\Elastica\Client\ElasticsearchClientFactory', 'createElasticsearchClient' ]
    arguments:
      $host: '%valantic_elastica_bridge.client.host%'
      $port: '%valantic_elastica_bridge.client.port%'
      $addSentryBreadcrumbs: '%valantic_elastica_bridge.client.addSentryBreadcrumbs%'

  Valantic\ElasticaBridgeBundle\Service\:
    resource: '../../Service/*'

  Valantic\ElasticaBridgeBundle\EventListener\:
    resource: '../../EventListener/*'

  Valantic\ElasticaBridgeBundle\Repository\IndexRepository:
    arguments:
      - !tagged_iterator valantic.elastica_bridge.index

  Valantic\ElasticaBridgeBundle\Repository\DocumentRepository:
    arguments:
      - !tagged_iterator valantic.elastica_bridge.document
